CREATE TABLE IF NOT EXISTS users
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name    VARCHAR(255) NOT NULL,
    email   VARCHAR(255) NOT NULL,
    surname VARCHAR(255) NOT NULL,
    PRIMARY KEY (id)
);

INSERT INTO users (name, surname, email) VALUES ('John', 'Doe', 'john.doe@gmail.com');
INSERT INTO users (name, surname, email) VALUES ('Jane', 'Doe', 'jane_doe@yandex.ru');
